openapi: 3.0.0
info:
  x-skaffolder-id-project: 5f6e10aa67541c707d17f2d6
  title: mkt
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  "/marketcontext/{id}":
    get:
      x-skaffolder-id: 5f6e110e67541c707d17f357
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5f6e110967541c707d17f353
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - MarketContext
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketContext"
  /marketcontext:
    get:
      x-skaffolder-id: 5f6e110e67541c707d17f35e
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5f6e110967541c707d17f353
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - MarketContext
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketContext"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MarketContext:
      x-skaffolder-id: 5f6e110967541c707d17f353
      x-skaffolder-id-db: 5f6e10aa67541c707d17f2d7
      x-skaffolder-id-entity: 5f6e110967541c707d17f351
      x-skaffolder-url: /marketcontext
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        tvalue:
          type: string
          x-skaffolder-id-attr: 5f6e110967541c707d17f352
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
  x-skaffolder-db:
    - x-skaffolder-id: 5f6e10aa67541c707d17f2d7
      x-skaffolder-name: mkt_db
  x-skaffolder-page:
    - x-skaffolder-id: 5f6e10aa67541c707d17f2df
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5f6e110e67541c707d17f35b
      x-skaffolder-roles: []
    - x-skaffolder-id: 5f6e110e67541c707d17f355
      x-skaffolder-name: MarketContextEdit
      x-skaffolder-url: /marketcontexts/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 5f6e110967541c707d17f353
      x-skaffolder-services:
        - 5f6e110e67541c707d17f357
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5f6e110e67541c707d17f35b
      x-skaffolder-name: MarketContextList
      x-skaffolder-url: /marketcontexts
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 5f6e110967541c707d17f353
      x-skaffolder-services:
        - 5f6e110e67541c707d17f35e
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5f6e110e67541c707d17f355
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 5f6e10aa67541c707d17f2e2
      x-skaffolder-name: ADMIN
