
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// MARKETCONTEXT
export const GET_MARKETCONTEXT_SUCCESS = "GET_MARKETCONTEXT_SUCCESS";
export const LIST_MARKETCONTEXT_SUCCESS = "LIST_MARKETCONTEXT_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
